@base = http://localhost:5282
@courseId = 3fa85f64-5717-4562-b3fc-2c963f66afa3


GET {{base}}/api/v1.0/basket/user/
Accept: application/json
###
POST {{base}}/api/v1.0/basket/item
Accept: application/json
Content-Type: application/json
{
  "courseId": "{{courseId}}",
  "courseName": "x3",
  "price": 100
}
###
DELETE {{base}}/api/v1.0/basket/item/{{courseId}}
Accept: application/json
Content-Type: application/json
###
PUT {{base}}/api/v1.0/basket/applydiscountrate
Accept: application/json
Content-Type: application/json
{
  "coupon": "abcdef",
  "rate": 0.1
}
###
DELETE {{base}}/api/v1.0/basket/rollbackdiscount
Accept: application/json
