global using MediatR;
global using AutoMapper;
global using Microsoft.EntityFrameworkCore;
global using UdemyMicroservice.Shared;
global using UdemyMicroservice.Shared.Extensions;
global using MassTransit;
global using System.Net;
global using FluentValidation;
global using UdemyMicroservice.Catalog.Api.Features.Categories.Dtos;
