@base = http://localhost:5027
@categoryId = 08de4895-9bfc-4437-5405-dbba7aef0000
@courseId = 08de4a47-902a-818b-5405-dbba7aef0000 
@userId = 7aef0000-dbba-5405-8357-08de4ab72b8b

GET {{base}}/api/v1.0/categories
Accept: application/json
###
POST {{base}}/api/categories
Accept: application/json
Content-Type: application/json
{
  "name": "Category 1"
}
###
GET {{base}}/api/categories/{{categoryId}}
Accept: application/json
###
DELETE {{base}}/api/categories/{{categoryId}}
Accept: application/json
###
PUT {{base}}/api/categories/
Accept: application/json
Content-Type: application/json
{
  "id": "{{categoryId}}",
  "name": "Update Deneme"
}
###
POST {{base}}/api/courses
Accept: application/json
Content-Type: application/json
{
  "name": "evlendirme2", 
  "description": "denemedescpdaasda", 
  "price": 120, 
  "imageUri": "örnek.resim",
  "categoryId": "{{categoryId}}"
}
###
GET {{base}}/api/courses
Accept: application/json
###
GET {{base}}/api/courses/{{courseId}}
Accept: application/json
###
PUT {{base}}/api/courses
Accept: application/json
Content-Type: application/json
{
  "id": "{{courseId}}",
  "name": "Update Deneme",
  "description": "deðiþti update",
  "price": 299.99,
  "imageUri": "http://updated",
  "categoryId": "{{categoryId}}"
}
###
DELETE {{base}}/api/courses /{{courseId}}
Accept: application/json
###
GET {{base}}/api/courses/user/{{userId}}
Accept: application/json
